### ISSUE TITLE
allow setting space to "closed" without inheriting it first

### ISSUE THREAD

**Issue by larsan** [Valodim/Stratum0Widget#3]
In the rare event that space has to be closed, the entity conducting the status-update might not necessarily be the entity on which the space is open at the time.
This might be for various reasons
* asked to inherit the status or just close when they leave by the second last entity (likely)
* opened the space with their bridged matrix representation in irc, so the saved nickname within the widget is not 100% equal to the nickname
* leaving at the same time with the current space status inheritor and selflessly carrying out the deed for them.
* "why is this space still open on x, they left middle of last week" (most likely)

Not all of these reasons represent the "how it should be" case, I admit.

Anyhow, the lack of this feature is the reason why I still have the old widget (which supports this) running parallel to this one.

Thanks ;)

**Comment by Valodim** [comment]
Sure. Done in next release
